### ISSUE TITLE
react-native-syan-image-picker库不支持ImagePickerOption(选择图片或数据的配置项)的minimumCompressSize属性，它的能力是：小于100kb的图片不压缩

### ISSUE THREAD

**Issue by zhang-hanyong** [react-native-oh-library/react-native-syan-image-picker#14]
Image-picker的实现，IOS依赖[TZImagePickerController](https://github.com/banchichen/TZImagePickerController)，Android依赖[PictureSelector](https://github.com/LuckSiege/PictureSelector)；

在HarmonyOSNEXT平台暂时没有适配PictureSelector、TZImagePickerController，当前策略是调用HarmonyOSNEXT平台的图片选择器，因此暂不支持此功能；

后续若要支持此功能，可考虑自定义实现图片选择器，从而支持此功能；

**Comment by wahaha150949** [comment]
ios 不支持，无需实现
